[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "true-lies-validator"
version = "0.5.2"
description = "True Lies - Separating truth from AI fiction. A powerful library for detecting LLM hallucinations and validating AI responses against factual data."
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["nltk"]
authors = [{name = "Pato Miner", email = "patominer@gmail.com"}]
keywords = ["llm", "validation", "hallucination-detection", "ai", "python", "truth-detection"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]

[tool.setuptools.package-data]
true_lies = ["semantic_data/*.json"]